#ifndef DOODLE_JUMP_CONSTS_H
#define DOODLE_JUMP_CONSTS_H

const int DOODLER_LEFT_SIZE = 20;
const int DOODLER_RIGHT_SIZE = 60;
const int DOODLER_DOWN_SIZE = 80;
const int PLATFORM_RIGHT_SIZE = 64;
const int PLATFORM_DOWN_SIZE = 14;
const int LIFTING_HEIGHT = 150;

#endif
